# Generated by Django 5.2.9 on 2026-01-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_calendarsubscriptiontoken'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calendarsubscriptiontoken',
            index=models.Index(fields=['token', 'is_active'], name='token_active_idx'),
        ),
    ]
