# Generated by Django 5.2.9 on 2026-02-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_calendarsubscriptiontoken_token_active_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarShare',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
