# Generated by Django 5.2.9 on 2026-03-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organization_user_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='identity email address'),
        ),
    ]
