name: Frontend Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  install-front:
    uses: ./.github/workflows/front-dependencies-installation.yml
    with:
      node_version: "24.x"

  lint-front:
    runs-on: ubuntu-latest
    needs: install-front
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
      - name: Enable pnpm via corepack
        run: corepack enable
      - name: Restore the frontend cache
        uses: actions/cache@v5
        with:
          path: "src/frontend/**/node_modules"
          key: front-node_modules-${{ hashFiles('src/frontend/**/pnpm-lock.yaml') }}
          fail-on-cache-miss: true

      - name: Check linting
        run: cd src/frontend/ && pnpm run lint

  test-front:
    runs-on: ubuntu-latest
    needs: install-front
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"

      - name: Enable pnpm via corepack
        run: corepack enable

      - name: Restore the frontend cache
        uses: actions/cache@v5
        with:
          path: "src/frontend/**/node_modules"
          key: front-node_modules-${{ hashFiles('src/frontend/**/pnpm-lock.yaml') }}
          fail-on-cache-miss: true

      - name: Run unit tests
        run: |
          cd src/frontend
          TZ=Europe/Paris pnpm test
